local fun = require("fun")()
local json = require("dkjson")
local ezhttp = require("ezhttp"):new()
print("start get")
ezhttp:getAsync("http://w3.impa.br/~diego/software/luasocket/http.html")
ezhttp:getAsync("http://w3.impa.br/~diego/software/luasocket/introduction.html")
ezhttp:getAsync("http://w3.impa.br/~diego/software/luasocket/home.html")
print("get finished")
res = ezhttp:waitOne()
for i,v in ipairs(res) do
	print("--------------------")
	print("res of " .. i)
	print(v.url)
	print(v.__stage)
	print(v.err)
	print(v.__status)
end
-- each(function(i,v) 
-- 		print(v.__stage)
-- 		print(v.__status)
-- 		print(v.err)
-- 	end	, res )
--print(ezhttp.solve("192.168.0.100"))
