local fun = require("fun")()
local json = require("dkjson")
local ezhttp = require("ezhttp")
print("start get")
ezhttp.getAsync("http://w3.impa.br/~diego/software/luasocket/http.html")
print("get finished")
res = ezhttp.waitAll()
each(function(i,v) 
		print(v.__stage)
		print(v.__status)
		print(v.err)
	end	, res )
--print(ezhttp.solve("192.168.0.100"))
