require("example")
AsyncWait()
--AsyncGetWaitOneExample()
--AsyncGetWaitAllExample()
--SyncGetExample()
-- local http1 = require("ezhttp"):new()
-- local http2 = require("ezhttp"):new()
-- local http3 = require("ezhttp"):new()