local http1 = require("ezhttp"):new("S1")
print("start async get")
http1:getAsync("http://w3.impa.br/~diego/software/luasocket/http.html")
http1:getAsync("http://w3.impa.br/~diego/software/luasocket/introduction.html")
http1:getAsync("http://w3.impa.br/~diego/software/luasocket/home.html")
print("async get finished")
res = http1:waitAll()

local http2 = require("ezhttp"):new("S2")
print("start async get")
http2:getAsync("http://w3.impa.br/~diego/software/luasocket/http.html")
http2:getAsync("http://w3.impa.br/~diego/software/luasocket/introduction.html")
http2:getAsync("http://w3.impa.br/~diego/software/luasocket/home.html")
print("async get finished")
res = http2:waitOne()

local http3 = require("ezhttp"):new("S3")
print("start async get")
http3:getAsync("http://w3.impa.br/~diego/software/luasocket/http.html")
http3:getAsync("http://w3.impa.br/~diego/software/luasocket/introduction.html")
http3:getAsync("http://w3.impa.br/~diego/software/luasocket/home.html")
print("async get finished")
res = http3:waitAll()